spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/h2
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true

