version: '2'
networks:
  my-network:
    driver: bridge

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    networks:
      my-network:
        aliases:
          - appService
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
      - activemq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_activemq_broker-url=tcp://activemq:61616
      - SPRING_activemq_user= admin
      - SPRING_activemq_password= admin
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    networks:
      my-network:
        aliases:
          - dbService
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres


  activemq:
    image: 'rmohr/activemq:latest'
    container_name: 'activemq'
    ports:
      - '8161:8161'
      - '61616:61616'
    networks:
      my-network:
        aliases:
          - mqService



#  activemq:
#    image: webcenter/activemq:5.14.3
#    container_name: activemq
#    ports:
#      # mqtt
#      - "1883:1883"
#      # amqp
#      - "5672:5672"
#      # ui
#      - "8161:8161"
#      # stomp
#      - "61613:61613"
#      # ws
#      - "61614:61614"
#      # jms
#      - "61616:61616"
##    networks: [ backing-services ]
##    volumes: [ "activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq" ]
#    environment:
##      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
##      ACTIVEMQ_ADMIN_LOGIN: admin
##      ACTIVEMQ_ADMIN_PASSWORD: password
##      ACTIVEMQ_WRITE_LOGIN: write
##      ACTIVEMQ_WRITE_PASSWORD: password
##      ACTIVEMQ_READ_LOGIN: read
##      ACTIVEMQ_READ_PASSWORD: password
##      ACTIVEMQ_JMX_LOGIN: jmx
##      ACTIVEMQ_JMX_PASSWORD: password
#      ACTIVEMQ_STATIC_QUEUES: input-queue;output-queue
#      ACTIVEMQ_ENABLED_SCHEDULER: "true"
#      ACTIVEMQ_MIN_MEMORY: 512
#      ACTIVEMQ_MAX_MEMORY: 2048